-- First Player Statements: fun prompts for deciding who goes first in a game
CREATE TABLE first_player_statements (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  statement TEXT NOT NULL,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE first_player_statements ENABLE ROW LEVEL SECURITY;

-- Everyone can read statements
CREATE POLICY "Anyone can read statements"
  ON first_player_statements FOR SELECT
  USING (true);

-- Only admins can insert/update/delete (via service role key in edge function)
-- No additional RLS policies needed since edge functions use service role

-- Seed the initial statements
INSERT INTO first_player_statements (statement) VALUES
  ('Whoever drank coffee most recently goes first'),
  ('Whoever woke up earliest today goes first'),
  ('Whoever last cooked a full meal goes first'),
  ('Whoever last did laundry goes first'),
  ('Whoever last cleaned something goes first'),
  ('Whoever last ate something spicy goes first'),
  ('Whoever last had dessert goes first'),
  ('Whoever last drank water goes first'),
  ('Whoever last ordered takeout goes first'),
  ('Whoever last tried a new food goes first'),
  ('Whoever last watched a movie goes first'),
  ('Whoever last played a video game goes first'),
  ('Whoever last sent a text message goes first'),
  ('Whoever last updated an app goes first'),
  ('Whoever last took a photo goes first'),
  ('Whoever last talked to a stranger goes first'),
  ('Whoever last traveled outside the city goes first'),
  ('Whoever last attended an event goes first'),
  ('Whoever last made someone laugh goes first'),
  ('Whoever last learned something new goes first'),
  ('Whoever last saw a bird goes first'),
  ('Whoever last forgot why they walked into a room goes first'),
  ('Whoever last lost something and found it again goes first'),
  ('Whoever last checked the time for no reason goes first'),
  ('Whoever last had a random song stuck in their head goes first'),
  ('Whoever exercised most recently goes first'),
  ('Whoever last won a game goes first'),
  ('Whoever last made a good decision goes first'),
  ('Whoever last procrastinated something goes first'),
  ('Whoever last felt lucky goes first'),
  ('Whoever last opened the fridge just to look goes first'),
  ('Whoever last checked the weather goes first'),
  ('Whoever last sat in silence doing nothing goes first'),
  ('Whoever last changed their clothes goes first'),
  ('Whoever last forgot to reply to a message goes first'),
  ('Whoever last Googled something pointless goes first'),
  ('Whoever last hit snooze goes first'),
  ('Whoever last refilled something goes first'),
  ('Whoever last tripped over nothing goes first'),
  ('Whoever last laughed at their own joke goes first'),
  ('Whoever last mispronounced a word confidently goes first'),
  ('Whoever last waved back at someone who wasn''t waving at them goes first'),
  ('Whoever last reread a message before sending it goes first'),
  ('Whoever last pretended to understand something goes first'),
  ('Whoever last ate standing up goes first'),
  ('Whoever last ate directly out of a container goes first'),
  ('Whoever last burned food goes first'),
  ('Whoever last forgot they had leftovers goes first'),
  ('Whoever last ate something past its expiration date goes first'),
  ('Whoever last had a midnight snack goes first'),
  ('Whoever last refreshed an app for no reason goes first'),
  ('Whoever last doomscrolled goes first'),
  ('Whoever last ignored a notification goes first'),
  ('Whoever last had low battery anxiety goes first'),
  ('Whoever last watched something at 2x speed goes first'),
  ('Whoever last opened too many tabs goes first'),
  ('Whoever last canceled plans goes first'),
  ('Whoever last made plans and kept them goes first'),
  ('Whoever last said we should hang out and didn''t follow up goes first'),
  ('Whoever last met someone new goes first'),
  ('Whoever last sent a meme goes first'),
  ('Whoever last saw a dog goes first'),
  ('Whoever last thought about space goes first'),
  ('Whoever last questioned their life choices goes first'),
  ('Whoever last looked for something they were holding goes first'),
  ('Whoever last opened a door and forgot why goes first'),
  ('Whoever last had a weird dream goes first'),
  ('Whoever feels the most confident right now goes first'),
  ('Whoever feels the least prepared goes first'),
  ('Whoever thinks they will win goes first'),
  ('Whoever last took a risk goes first'),
  ('Whoever last changed their mind goes first'),
  ('Whoever arrived here most recently goes first'),
  ('Whoever traveled the farthest to get here goes first'),
  ('Whoever is sitting closest to the door goes first'),
  ('Whoever has the most items in their pockets goes first'),
  ('Whoever has the brightest clothing goes first'),
  ('Whoever blinked last goes first'),
  ('Whoever spoke most recently goes first'),
  ('Whoever''s phone battery is lowest goes first'),
  ('Whoever is thinking about food right now goes first'),
  ('Whoever smiled last goes first'),
  ('Whoever checked the time most recently goes first');
